FROM phusion/baseimage:0.11
MAINTAINER Matt McCormick "matt.mccormick@kitware.com"

#include "common.debian"

#include "common.dockcross"

COPY imagefiles/entrypoint.py /sbin/entrypoint-dockcross
# ENTRYPOINT ["/sbin/entrypoint-dockcross"]
ENTRYPOINT ["/sbin/entrypoint-dockcross", "/dockcross/entrypoint.sh"]
# CMD ["/sbin/my_init", "--quiet", "--skip-startup-files", "--", "/dockcross/entrypoint.sh"]

# Build-time metadata as defined at http://label-schema.org
# Note: To avoid systematic rebuild of dependent images, only
#       name and vcs-url are included.
ARG IMAGE
ARG VCS_URL
LABEL org.label-schema.name=$IMAGE \
      org.label-schema.vcs-url=$VCS_URL \
      org.label-schema.schema-version="1.0"
